version: 2
jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:bionic"

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update -q --yes
      - run: sudo apt-get -q --yes install openjdk-8-jdk
      - run: sudo apt-get -q --yes install maven
      - run: sudo apt-get -q --yes install python
      - run: sudo apt-get -q --yes install python-pip
      - run: sudo apt-get -q --yes install cmake
      - run: cd native && ./build.sh

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn -q dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      - run: mvn -q surefire-report:report

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      - store_artifacts:
          path: src/main/resources/META-INF/duktape.so
          destination: duktape.so
